# 인덱싱 연습하기


In [10]:
import numpy as np

# 기준이 될 4x4 배열 생성 (이미지와 동일하게 0부터 15까지의 숫자로 채움)
arr_2d = np.arange(16).reshape((4, 4))

print("원본 4x4 배열:")
print(arr_2d)
print("-" * 30)

원본 4x4 배열:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
------------------------------


In [13]:
# 첫 번째 행 전체
first_row = arr_2d[0, :]  

print("첫 번째 행:")
print(first_row)

첫 번째 행:
[0 1 2 3]


In [ ]:
#마지막 열 전체
last_row = arr_2d[:, -1]  
 # last_row = arr_2d[:, 3]
print("마지막 열 전체:")
print(last_row)

마지막 열 전체:
[ 3  7 11 15]


In [17]:
#첫 번째 행과 마지막 행만 선택, 각 행의 첫번째 열, 마지막 열 선택
import numpy as np

arr_2d = np.arange(16).reshape((4, 4))

print("원본 배열:")
print(arr_2d)
print("-" * 30)

# 첫 번째 행과 마지막 행에서 첫 번째 열, 마지막 열만 선택
result = arr_2d[[0, -1], :][:, [0, -1]]

print("선택된 결과:")
print(result)


원본 배열:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
------------------------------
선택된 결과:
[[ 0  3]
 [12 15]]


In [5]:
# 짝수 인덱스 행(0번째, 2번째 행), 홀수 인덱스 열 선택


In [6]:
#위의 3차원 행렬을 작성하세요


In [7]:
# 2번째 층 선택


In [ ]:
#네번째행, 두번째 열 원소 선택, 1차원 배열로 작성


In [ ]:
#배열의 첫 두 층, 마지막 두 행, 마지막 두 열 선택


In [ ]:
#짝수 인덱스층, 모든행의 세번째열 선택


In [8]:
#세번째 층, 두번째 행에서 네번째 행, 홀수 인덱스 열